name: org_parser_example
description: Demonstrates how to use the org_parser plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  http: ^0.13.1
  http_retry: ^0.2.0
  state_notifier: ^0.7.0
  flutter_state_notifier: ^0.7.0
  freezed_annotation: ^0.14.1
  flutter_launcher_icons: ^0.9.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  build_runner:
  freezed: ^0.14.1+1

  org_parser:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Myrica
      fonts:
        - asset: assets/fonts/myrica/Myrica.TTC
    - family: Cica
      fonts:
        - asset: assets/fonts/cica/Cica-Regular.ttf
    - family: SourceHanCodeJP
      fonts:
        - asset: assets/fonts/source-han-code-jp/SourceHanCodeJP.ttc
    - family: HackGen
      fonts:
        - asset: assets/fonts/hackgen/HackGen-Regular.ttf

flutter_icons:
  android: false
  ios: true
  image_path: "android/app/src/main/ic_launcher-web.png"
