name: orgcal
description: "Org-mode calendar app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  shared_preferences_platform_interface: ^2.4.1
  provider: ^5.0.0
  http: ^0.13.1
  http_retry: ^0.2.0
  state_notifier: ^0.7.0
  flutter_state_notifier: ^0.7.0
  freezed_annotation: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  intl: ^0.19.0
  org_parser:
    git: https://github.com/yuzumone/org_parser.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Myrica
      fonts:
        - asset: assets/fonts/myrica/Myrica.TTC
    - family: Cica
      fonts:
        - asset: assets/fonts/cica/Cica-Regular.ttf
    - family: SourceHanCodeJP
      fonts:
        - asset: assets/fonts/source-han-code-jp/SourceHanCodeJP.ttc
    - family: HackGen
      fonts:
        - asset: assets/fonts/hackgen/HackGen-Regular.ttf

flutter_icons:
  android: false
  ios: true
  image_path: "android/app/src/main/ic_launcher-web.png"
