name: test and lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - name: pub get
        run: flutter pub get
      - name: format
        run: dart format --set-exit-if-changed .
      - name: analyze
        run: flutter analyze
      - name: test
        run: flutter test --verbose
      - name: build test
        run: flutter build apk --debug
